// AUTO-GENERATED from docs/curated-msrp.csv by scripts/gen-curated-msrp.mjs — DO NOT EDIT BY HAND.
// Regenerate: `node scripts/gen-curated-msrp.mjs`. Drift-guarded by curatedMsrp.drift.test.js.
//
// Curated MSRP lookup — a static, research-derived retail table (sourced + estimated tiers),
// independent of BrickEconomy / Phase 3c: bundled, no network, never source:"brickeconomy".
// Mirrors cmfRetail.js (pure lookup). tier "none" rows (no standalone MSRP, e.g. 30625) are
// OMITTED here → curatedRetail() returns null → the set stays "not listed".
export const CURATED_MSRP = {
  "30002-1": { msrp: 2.99, tier: "sourced", confidence: "B", source: "Brickset RRP" },
  "30303-1": { msrp: 3.99, tier: "sourced", confidence: "B", source: "Brickset website RRP (verified live)" },
  "30352-1": { msrp: 3.99, tier: "estimated", confidence: "C", source: "Retail polybag standard / older City polybag proxy" },
  "30370-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30383-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30420-1": { msrp: 4.99, tier: "sourced", confidence: "B", source: "BrickEconomy original retail price" },
  "30434-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30435-1": { msrp: 4.99, tier: "sourced", confidence: "B", source: "Brickset website RRP (verified live)" },
  "30455-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30495-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30543-1": { msrp: 3.99, tier: "sourced", confidence: "B", source: "BrickEconomy retail price" },
  "30559-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30566-1": { msrp: 4.68, tier: "sourced", confidence: "B", source: "converted (UK→USD); Brickset UK RRP £3.49×1.34" },
  "30570-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30580-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30581-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30584-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30585-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30589-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30590-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30635-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30645-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30649-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30650-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30651-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30652-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30653-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30654-1": { msrp: 4.99, tier: "sourced", confidence: "A", source: "Official LEGO product page / BrickEconomy" },
  "30663-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30665-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30668-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30672-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30675-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30677-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30679-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30680-1": { msrp: 4.99, tier: "sourced", confidence: "B", source: "Brickset website RRP (verified live)" },
  "30683-1": { msrp: 4.99, tier: "sourced", confidence: "A", source: "Official LEGO product page / BrickEconomy" },
  "30685-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30689-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30694-1": { msrp: 4.99, tier: "sourced", confidence: "B", source: "BrickEconomy / official LEGO instructions page" },
  "30706-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30708-1": { msrp: 4.99, tier: "sourced", confidence: "B", source: "Brickset website RRP (verified live)" },
  "30709-1": { msrp: 4.99, tier: "sourced", confidence: "A", source: "Official LEGO product page / BrickEconomy" },
  "30716-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30719-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30723-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30727-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "30734-1": { msrp: 4.99, tier: "estimated", confidence: "C", source: "Retail polybag standard" },
  "40416-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickset/current value proxy" },
  "40452-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40484-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Seasonal boxed GWP value proxy" },
  "40527-1": { msrp: 14.99, tier: "estimated", confidence: "C", source: "BrickEconomy/market value proxy" },
  "40531-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40563-1": { msrp: 29.99, tier: "sourced", confidence: "A", source: "LEGO product page / stated value" },
  "40564-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40565-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "LEGO product page" },
  "40566-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40567-1": { msrp: 24.99, tier: "sourced", confidence: "A", source: "LEGO product page" },
  "40577-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40580-1": { msrp: 29.99, tier: "sourced", confidence: "B", source: "Archived LEGO promo terms quoted by Investabrick" },
  "40584-1": { msrp: 12.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40585-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40587-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO product page" },
  "40591-1": { msrp: 39.99, tier: "estimated", confidence: "C", source: "Brickset/market value proxy; no official ARV found" },
  "40595-1": { msrp: 24.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40599-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickwatch LEGO retail price (secondary)" },
  "40601-1": { msrp: 29.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40602-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Brickfact RRP (secondary)" },
  "40603-1": { msrp: 22.99, tier: "estimated", confidence: "D", source: "Brickipedia price (secondary)" },
  "40604-1": { msrp: 14.99, tier: "estimated", confidence: "C", source: "Seasonal decor GWP value proxy" },
  "40606-1": { msrp: 9.99, tier: "sourced", confidence: "A", source: "LEGO product page" },
  "40607-1": { msrp: 9.99, tier: "estimated", confidence: "D", source: "Inferred from VIP Add-On Pack line / comparable LEGO page" },
  "40609-1": { msrp: 9.99, tier: "estimated", confidence: "C", source: "LEGO product page / community checkout value" },
  "40659-1": { msrp: 24.99, tier: "estimated", confidence: "C", source: "Brickfact LEGO retail price listing" },
  "40682-1": { msrp: 14.99, tier: "estimated", confidence: "C", source: "Brickset/market value proxy" },
  "40686-1": { msrp: 29.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Store Events page)" },
  "40687-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "LEGO product page" },
  "40689-1": { msrp: 14.99, tier: "sourced", confidence: "A", source: "LEGO event page ARV" },
  "40695-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO product page" },
  "40700-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Insiders Weekend page)" },
  "40701-1": { msrp: 22.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Store Events page)" },
  "40703-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Micro NINJAGO reward value proxy" },
  "40704-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Micro NINJAGO reward value proxy" },
  "40705-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Micro NINJAGO reward value proxy" },
  "40706-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Micro NINJAGO reward value proxy" },
  "40712-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "LEGO product page / boxed space GWP value proxy" },
  "40728-1": { msrp: 9.99, tier: "estimated", confidence: "C", source: "BrickHeadz standard MSRP proxy" },
  "40761-1": { msrp: 24.99, tier: "sourced", confidence: "A", source: "Official LEGO product page" },
  "40764-1": { msrp: 19.99, tier: "sourced", confidence: "B", source: "Official LEGO product page price" },
  "40765-1": { msrp: 29.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Terms & Conditions)" },
  "40767-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Secondary page quoting LEGO promo terms" },
  "40768-1": { msrp: 24.99, tier: "estimated", confidence: "D", source: "Search result / social repost quoting LEGO promo terms" },
  "40769-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO product page" },
  "40770-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Comparable LEGO HP GWP value / secondary documentation" },
  "40772-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Secondary page quoting LEGO promo terms" },
  "40773-1": { msrp: 39.99, tier: "estimated", confidence: "C", source: "LEGO product page + reported LEGO site value" },
  "40774-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Terms & Conditions)" },
  "40775-1": { msrp: 29.99, tier: "estimated", confidence: "D", source: "Search result / social repost quoting LEGO promo terms" },
  "40776-1": { msrp: 39.99, tier: "estimated", confidence: "D", source: "Regional LEGO promo doc via Scribd" },
  "40778-1": { msrp: 22.99, tier: "sourced", confidence: "A", source: "Official LEGO product page" },
  "40786-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Insiders points redemption value / LEGO product page" },
  "40789-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "Insiders points redemption value / LEGO product page" },
  "40885-1": { msrp: 19.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Terms & Conditions)" },
  "40917-1": { msrp: 29.99, tier: "sourced", confidence: "A", source: "Official LEGO ARV (US Terms & Conditions)" },
  "122405-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "242401-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "552402-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "552405-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "892403-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "912403-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "952302-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "952403-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "952411-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify" },
  "5007427-1": { msrp: 22.99, tier: "sourced", confidence: "B", source: "Brickfact RRP" },
  "5007428-1": { msrp: 22.99, tier: "sourced", confidence: "B", source: "Brickfact RRP" },
  "5007489-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "VIP points redemption value" },
  "5007490-1": { msrp: 19.99, tier: "estimated", confidence: "C", source: "VIP points redemption value / review receipt value" },
  "5008074-1": { msrp: 12.99, tier: "estimated", confidence: "D", source: "Insiders reward / comparable small buildable reward" },
  "5008897-1": { msrp: 9.99, tier: "estimated", confidence: "D", source: "Insiders reward / comparable game reward" },
  "5009378-1": { msrp: 12.99, tier: "estimated", confidence: "D", source: "Best Buy/LEGO promo value proxy" },
  "5009614-1": { msrp: 9.99, tier: "estimated", confidence: "D", source: "LEGO promo value proxy" },
  "5009806-1": { msrp: 12.99, tier: "estimated", confidence: "D", source: "LEGO promo value proxy" },
  "6426244-1": { msrp: 12.99, tier: "estimated", confidence: "D", source: "90th anniversary mini promo value proxy" },
  "6490363-1": { msrp: 19.99, tier: "estimated", confidence: "D", source: "Seasonal GWP value proxy" },
  "6550806-1": { msrp: 19.99, tier: "estimated", confidence: "D", source: "Seasonal GWP value proxy" },
  "L0002221-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify (2026 — may be unreleased/unpriced)" },
  "L0002232-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify (2026 — may be unreleased/unpriced)" },
  "L0002288-1": { msrp: 7.37, tier: "estimated", confidence: "C", source: "est. UK LEGO magazine cover price ~£5.50 × 1.34; per-issue varies £4.50–£5.99 — verify (2026 — may be unreleased/unpriced)" },
};

/**
 * Curated retail for an owned set number → { msrp, tier, confidence, source } | null.
 * tier: "sourced" (researched real RRP / LEGO-stated value) | "estimated" (proxy/ARV). The
 * retail ladder (retailFor) routes sourced → basis "retail", estimated → basis "estimated";
 * a promo (isPromoNoRetail) set's curated value stays basis "promo" (a valued GWP ARV).
 *
 * @param {string} setNumber  e.g. "30303-1".
 * @returns {{ msrp:number, tier:"sourced"|"estimated", confidence:string, source:string } | null}
 */
export function curatedRetail(setNumber) {
  return CURATED_MSRP[setNumber] || null;
}
